/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NameRouteImport } from './routes/$name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as NameIndexRouteImport } from './routes/$name/index'
import { Route as TldTldRouteImport } from './routes/tld/$tld'
import { Route as ResolverAddressRouteImport } from './routes/resolver/$address'
import { Route as RegistryAddressRouteImport } from './routes/registry/$address'
import { Route as AddrAddrRouteImport } from './routes/addr/$addr'
import { Route as NameTokenRouteImport } from './routes/$name/token'
import { Route as NameSubnamesRouteImport } from './routes/$name/subnames'
import { Route as NameResolverRouteImport } from './routes/$name/resolver'
import { Route as NameRegistryRouteImport } from './routes/$name/registry'
import { Route as NameRecordsRouteImport } from './routes/$name/records'
import { Route as NameHistoryRouteImport } from './routes/$name/history'
import { Route as NameEditRecordsRouteImport } from './routes/$name/edit-records'
import { Route as NameCreateSubnameRouteImport } from './routes/$name/create-subname'
import { Route as NameChangeResolverRouteImport } from './routes/$name/change-resolver'
import { Route as NameAddressRouteImport } from './routes/$name/address'
import { Route as TldTldIndexRouteImport } from './routes/tld/$tld/index'
import { Route as ResolverAddressIndexRouteImport } from './routes/resolver/$address/index'
import { Route as RegistryAddressIndexRouteImport } from './routes/registry/$address/index'
import { Route as AddrAddrIndexRouteImport } from './routes/addr/$addr/index'
import { Route as NameRolesIndexRouteImport } from './routes/$name/roles/index'
import { Route as NameOwnershipIndexRouteImport } from './routes/$name/ownership/index'
import { Route as NameFusesIndexRouteImport } from './routes/$name/fuses/index'
import { Route as ResolverAddressNodesRouteImport } from './routes/resolver/$address/nodes'
import { Route as ResolverAddressHistoryRouteImport } from './routes/resolver/$address/history'
import { Route as ResolverAddressCreateAliasRouteImport } from './routes/resolver/$address/create-alias'
import { Route as ResolverAddressAliasesRouteImport } from './routes/resolver/$address/aliases'
import { Route as RegistryAddressRolesRouteImport } from './routes/registry/$address/roles'
import { Route as RegistryAddressLabelsRouteImport } from './routes/registry/$address/labels'
import { Route as RegistryAddressHistoryRouteImport } from './routes/registry/$address/history'
import { Route as AddrAddrReverseResolutionRouteImport } from './routes/addr/$addr/reverse-resolution'
import { Route as AddrAddrResolutionRouteImport } from './routes/addr/$addr/resolution'
import { Route as AddrAddrNamesRouteImport } from './routes/addr/$addr/names'
import { Route as AddrAddrHistoryRouteImport } from './routes/addr/$addr/history'
import { Route as NameOwnershipTransferRouteImport } from './routes/$name/ownership/transfer'
import { Route as NameFusesBurnRouteImport } from './routes/$name/fuses/burn'
import { Route as ResolverAddressRolesIndexRouteImport } from './routes/resolver/$address/roles/index'

const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const NameIndexRoute = NameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NameRoute,
} as any)
const TldTldRoute = TldTldRouteImport.update({
  id: '/tld/$tld',
  path: '/tld/$tld',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolverAddressRoute = ResolverAddressRouteImport.update({
  id: '/resolver/$address',
  path: '/resolver/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryAddressRoute = RegistryAddressRouteImport.update({
  id: '/registry/$address',
  path: '/registry/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const AddrAddrRoute = AddrAddrRouteImport.update({
  id: '/addr/$addr',
  path: '/addr/$addr',
  getParentRoute: () => rootRouteImport,
} as any)
const NameTokenRoute = NameTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => NameRoute,
} as any)
const NameSubnamesRoute = NameSubnamesRouteImport.update({
  id: '/subnames',
  path: '/subnames',
  getParentRoute: () => NameRoute,
} as any)
const NameResolverRoute = NameResolverRouteImport.update({
  id: '/resolver',
  path: '/resolver',
  getParentRoute: () => NameRoute,
} as any)
const NameRegistryRoute = NameRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => NameRoute,
} as any)
const NameRecordsRoute = NameRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => NameRoute,
} as any)
const NameHistoryRoute = NameHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => NameRoute,
} as any)
const NameEditRecordsRoute = NameEditRecordsRouteImport.update({
  id: '/edit-records',
  path: '/edit-records',
  getParentRoute: () => NameRoute,
} as any)
const NameCreateSubnameRoute = NameCreateSubnameRouteImport.update({
  id: '/create-subname',
  path: '/create-subname',
  getParentRoute: () => NameRoute,
} as any)
const NameChangeResolverRoute = NameChangeResolverRouteImport.update({
  id: '/change-resolver',
  path: '/change-resolver',
  getParentRoute: () => NameRoute,
} as any)
const NameAddressRoute = NameAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => NameRoute,
} as any)
const TldTldIndexRoute = TldTldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TldTldRoute,
} as any)
const ResolverAddressIndexRoute = ResolverAddressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResolverAddressRoute,
} as any)
const RegistryAddressIndexRoute = RegistryAddressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegistryAddressRoute,
} as any)
const AddrAddrIndexRoute = AddrAddrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AddrAddrRoute,
} as any)
const NameRolesIndexRoute = NameRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => NameRoute,
} as any)
const NameOwnershipIndexRoute = NameOwnershipIndexRouteImport.update({
  id: '/ownership/',
  path: '/ownership/',
  getParentRoute: () => NameRoute,
} as any)
const NameFusesIndexRoute = NameFusesIndexRouteImport.update({
  id: '/fuses/',
  path: '/fuses/',
  getParentRoute: () => NameRoute,
} as any)
const ResolverAddressNodesRoute = ResolverAddressNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => ResolverAddressRoute,
} as any)
const ResolverAddressHistoryRoute = ResolverAddressHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ResolverAddressRoute,
} as any)
const ResolverAddressCreateAliasRoute =
  ResolverAddressCreateAliasRouteImport.update({
    id: '/create-alias',
    path: '/create-alias',
    getParentRoute: () => ResolverAddressRoute,
  } as any)
const ResolverAddressAliasesRoute = ResolverAddressAliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => ResolverAddressRoute,
} as any)
const RegistryAddressRolesRoute = RegistryAddressRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => RegistryAddressRoute,
} as any)
const RegistryAddressLabelsRoute = RegistryAddressLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => RegistryAddressRoute,
} as any)
const RegistryAddressHistoryRoute = RegistryAddressHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RegistryAddressRoute,
} as any)
const AddrAddrReverseResolutionRoute =
  AddrAddrReverseResolutionRouteImport.update({
    id: '/reverse-resolution',
    path: '/reverse-resolution',
    getParentRoute: () => AddrAddrRoute,
  } as any)
const AddrAddrResolutionRoute = AddrAddrResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => AddrAddrRoute,
} as any)
const AddrAddrNamesRoute = AddrAddrNamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => AddrAddrRoute,
} as any)
const AddrAddrHistoryRoute = AddrAddrHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AddrAddrRoute,
} as any)
const NameOwnershipTransferRoute = NameOwnershipTransferRouteImport.update({
  id: '/ownership/transfer',
  path: '/ownership/transfer',
  getParentRoute: () => NameRoute,
} as any)
const NameFusesBurnRoute = NameFusesBurnRouteImport.update({
  id: '/fuses/burn',
  path: '/fuses/burn',
  getParentRoute: () => NameRoute,
} as any)
const ResolverAddressRolesIndexRoute =
  ResolverAddressRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => ResolverAddressRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRouteWithChildren
  '/$name/address': typeof NameAddressRoute
  '/$name/change-resolver': typeof NameChangeResolverRoute
  '/$name/create-subname': typeof NameCreateSubnameRoute
  '/$name/edit-records': typeof NameEditRecordsRoute
  '/$name/history': typeof NameHistoryRoute
  '/$name/records': typeof NameRecordsRoute
  '/$name/registry': typeof NameRegistryRoute
  '/$name/resolver': typeof NameResolverRoute
  '/$name/subnames': typeof NameSubnamesRoute
  '/$name/token': typeof NameTokenRoute
  '/addr/$addr': typeof AddrAddrRouteWithChildren
  '/registry/$address': typeof RegistryAddressRouteWithChildren
  '/resolver/$address': typeof ResolverAddressRouteWithChildren
  '/tld/$tld': typeof TldTldRouteWithChildren
  '/$name/': typeof NameIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/$name/fuses/burn': typeof NameFusesBurnRoute
  '/$name/ownership/transfer': typeof NameOwnershipTransferRoute
  '/addr/$addr/history': typeof AddrAddrHistoryRoute
  '/addr/$addr/names': typeof AddrAddrNamesRoute
  '/addr/$addr/resolution': typeof AddrAddrResolutionRoute
  '/addr/$addr/reverse-resolution': typeof AddrAddrReverseResolutionRoute
  '/registry/$address/history': typeof RegistryAddressHistoryRoute
  '/registry/$address/labels': typeof RegistryAddressLabelsRoute
  '/registry/$address/roles': typeof RegistryAddressRolesRoute
  '/resolver/$address/aliases': typeof ResolverAddressAliasesRoute
  '/resolver/$address/create-alias': typeof ResolverAddressCreateAliasRoute
  '/resolver/$address/history': typeof ResolverAddressHistoryRoute
  '/resolver/$address/nodes': typeof ResolverAddressNodesRoute
  '/$name/fuses/': typeof NameFusesIndexRoute
  '/$name/ownership/': typeof NameOwnershipIndexRoute
  '/$name/roles/': typeof NameRolesIndexRoute
  '/addr/$addr/': typeof AddrAddrIndexRoute
  '/registry/$address/': typeof RegistryAddressIndexRoute
  '/resolver/$address/': typeof ResolverAddressIndexRoute
  '/tld/$tld/': typeof TldTldIndexRoute
  '/resolver/$address/roles/': typeof ResolverAddressRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name/address': typeof NameAddressRoute
  '/$name/change-resolver': typeof NameChangeResolverRoute
  '/$name/create-subname': typeof NameCreateSubnameRoute
  '/$name/edit-records': typeof NameEditRecordsRoute
  '/$name/history': typeof NameHistoryRoute
  '/$name/records': typeof NameRecordsRoute
  '/$name/registry': typeof NameRegistryRoute
  '/$name/resolver': typeof NameResolverRoute
  '/$name/subnames': typeof NameSubnamesRoute
  '/$name/token': typeof NameTokenRoute
  '/$name': typeof NameIndexRoute
  '/register': typeof RegisterIndexRoute
  '/$name/fuses/burn': typeof NameFusesBurnRoute
  '/$name/ownership/transfer': typeof NameOwnershipTransferRoute
  '/addr/$addr/history': typeof AddrAddrHistoryRoute
  '/addr/$addr/names': typeof AddrAddrNamesRoute
  '/addr/$addr/resolution': typeof AddrAddrResolutionRoute
  '/addr/$addr/reverse-resolution': typeof AddrAddrReverseResolutionRoute
  '/registry/$address/history': typeof RegistryAddressHistoryRoute
  '/registry/$address/labels': typeof RegistryAddressLabelsRoute
  '/registry/$address/roles': typeof RegistryAddressRolesRoute
  '/resolver/$address/aliases': typeof ResolverAddressAliasesRoute
  '/resolver/$address/create-alias': typeof ResolverAddressCreateAliasRoute
  '/resolver/$address/history': typeof ResolverAddressHistoryRoute
  '/resolver/$address/nodes': typeof ResolverAddressNodesRoute
  '/$name/fuses': typeof NameFusesIndexRoute
  '/$name/ownership': typeof NameOwnershipIndexRoute
  '/$name/roles': typeof NameRolesIndexRoute
  '/addr/$addr': typeof AddrAddrIndexRoute
  '/registry/$address': typeof RegistryAddressIndexRoute
  '/resolver/$address': typeof ResolverAddressIndexRoute
  '/tld/$tld': typeof TldTldIndexRoute
  '/resolver/$address/roles': typeof ResolverAddressRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRouteWithChildren
  '/$name/address': typeof NameAddressRoute
  '/$name/change-resolver': typeof NameChangeResolverRoute
  '/$name/create-subname': typeof NameCreateSubnameRoute
  '/$name/edit-records': typeof NameEditRecordsRoute
  '/$name/history': typeof NameHistoryRoute
  '/$name/records': typeof NameRecordsRoute
  '/$name/registry': typeof NameRegistryRoute
  '/$name/resolver': typeof NameResolverRoute
  '/$name/subnames': typeof NameSubnamesRoute
  '/$name/token': typeof NameTokenRoute
  '/addr/$addr': typeof AddrAddrRouteWithChildren
  '/registry/$address': typeof RegistryAddressRouteWithChildren
  '/resolver/$address': typeof ResolverAddressRouteWithChildren
  '/tld/$tld': typeof TldTldRouteWithChildren
  '/$name/': typeof NameIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/$name/fuses/burn': typeof NameFusesBurnRoute
  '/$name/ownership/transfer': typeof NameOwnershipTransferRoute
  '/addr/$addr/history': typeof AddrAddrHistoryRoute
  '/addr/$addr/names': typeof AddrAddrNamesRoute
  '/addr/$addr/resolution': typeof AddrAddrResolutionRoute
  '/addr/$addr/reverse-resolution': typeof AddrAddrReverseResolutionRoute
  '/registry/$address/history': typeof RegistryAddressHistoryRoute
  '/registry/$address/labels': typeof RegistryAddressLabelsRoute
  '/registry/$address/roles': typeof RegistryAddressRolesRoute
  '/resolver/$address/aliases': typeof ResolverAddressAliasesRoute
  '/resolver/$address/create-alias': typeof ResolverAddressCreateAliasRoute
  '/resolver/$address/history': typeof ResolverAddressHistoryRoute
  '/resolver/$address/nodes': typeof ResolverAddressNodesRoute
  '/$name/fuses/': typeof NameFusesIndexRoute
  '/$name/ownership/': typeof NameOwnershipIndexRoute
  '/$name/roles/': typeof NameRolesIndexRoute
  '/addr/$addr/': typeof AddrAddrIndexRoute
  '/registry/$address/': typeof RegistryAddressIndexRoute
  '/resolver/$address/': typeof ResolverAddressIndexRoute
  '/tld/$tld/': typeof TldTldIndexRoute
  '/resolver/$address/roles/': typeof ResolverAddressRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$name'
    | '/$name/address'
    | '/$name/change-resolver'
    | '/$name/create-subname'
    | '/$name/edit-records'
    | '/$name/history'
    | '/$name/records'
    | '/$name/registry'
    | '/$name/resolver'
    | '/$name/subnames'
    | '/$name/token'
    | '/addr/$addr'
    | '/registry/$address'
    | '/resolver/$address'
    | '/tld/$tld'
    | '/$name/'
    | '/register/'
    | '/$name/fuses/burn'
    | '/$name/ownership/transfer'
    | '/addr/$addr/history'
    | '/addr/$addr/names'
    | '/addr/$addr/resolution'
    | '/addr/$addr/reverse-resolution'
    | '/registry/$address/history'
    | '/registry/$address/labels'
    | '/registry/$address/roles'
    | '/resolver/$address/aliases'
    | '/resolver/$address/create-alias'
    | '/resolver/$address/history'
    | '/resolver/$address/nodes'
    | '/$name/fuses/'
    | '/$name/ownership/'
    | '/$name/roles/'
    | '/addr/$addr/'
    | '/registry/$address/'
    | '/resolver/$address/'
    | '/tld/$tld/'
    | '/resolver/$address/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$name/address'
    | '/$name/change-resolver'
    | '/$name/create-subname'
    | '/$name/edit-records'
    | '/$name/history'
    | '/$name/records'
    | '/$name/registry'
    | '/$name/resolver'
    | '/$name/subnames'
    | '/$name/token'
    | '/$name'
    | '/register'
    | '/$name/fuses/burn'
    | '/$name/ownership/transfer'
    | '/addr/$addr/history'
    | '/addr/$addr/names'
    | '/addr/$addr/resolution'
    | '/addr/$addr/reverse-resolution'
    | '/registry/$address/history'
    | '/registry/$address/labels'
    | '/registry/$address/roles'
    | '/resolver/$address/aliases'
    | '/resolver/$address/create-alias'
    | '/resolver/$address/history'
    | '/resolver/$address/nodes'
    | '/$name/fuses'
    | '/$name/ownership'
    | '/$name/roles'
    | '/addr/$addr'
    | '/registry/$address'
    | '/resolver/$address'
    | '/tld/$tld'
    | '/resolver/$address/roles'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/$name/address'
    | '/$name/change-resolver'
    | '/$name/create-subname'
    | '/$name/edit-records'
    | '/$name/history'
    | '/$name/records'
    | '/$name/registry'
    | '/$name/resolver'
    | '/$name/subnames'
    | '/$name/token'
    | '/addr/$addr'
    | '/registry/$address'
    | '/resolver/$address'
    | '/tld/$tld'
    | '/$name/'
    | '/register/'
    | '/$name/fuses/burn'
    | '/$name/ownership/transfer'
    | '/addr/$addr/history'
    | '/addr/$addr/names'
    | '/addr/$addr/resolution'
    | '/addr/$addr/reverse-resolution'
    | '/registry/$address/history'
    | '/registry/$address/labels'
    | '/registry/$address/roles'
    | '/resolver/$address/aliases'
    | '/resolver/$address/create-alias'
    | '/resolver/$address/history'
    | '/resolver/$address/nodes'
    | '/$name/fuses/'
    | '/$name/ownership/'
    | '/$name/roles/'
    | '/addr/$addr/'
    | '/registry/$address/'
    | '/resolver/$address/'
    | '/tld/$tld/'
    | '/resolver/$address/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRouteWithChildren
  AddrAddrRoute: typeof AddrAddrRouteWithChildren
  RegistryAddressRoute: typeof RegistryAddressRouteWithChildren
  ResolverAddressRoute: typeof ResolverAddressRouteWithChildren
  TldTldRoute: typeof TldTldRouteWithChildren
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name/': {
      id: '/$name/'
      path: '/'
      fullPath: '/$name/'
      preLoaderRoute: typeof NameIndexRouteImport
      parentRoute: typeof NameRoute
    }
    '/tld/$tld': {
      id: '/tld/$tld'
      path: '/tld/$tld'
      fullPath: '/tld/$tld'
      preLoaderRoute: typeof TldTldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolver/$address': {
      id: '/resolver/$address'
      path: '/resolver/$address'
      fullPath: '/resolver/$address'
      preLoaderRoute: typeof ResolverAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/$address': {
      id: '/registry/$address'
      path: '/registry/$address'
      fullPath: '/registry/$address'
      preLoaderRoute: typeof RegistryAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addr/$addr': {
      id: '/addr/$addr'
      path: '/addr/$addr'
      fullPath: '/addr/$addr'
      preLoaderRoute: typeof AddrAddrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name/token': {
      id: '/$name/token'
      path: '/token'
      fullPath: '/$name/token'
      preLoaderRoute: typeof NameTokenRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/subnames': {
      id: '/$name/subnames'
      path: '/subnames'
      fullPath: '/$name/subnames'
      preLoaderRoute: typeof NameSubnamesRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/resolver': {
      id: '/$name/resolver'
      path: '/resolver'
      fullPath: '/$name/resolver'
      preLoaderRoute: typeof NameResolverRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/registry': {
      id: '/$name/registry'
      path: '/registry'
      fullPath: '/$name/registry'
      preLoaderRoute: typeof NameRegistryRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/records': {
      id: '/$name/records'
      path: '/records'
      fullPath: '/$name/records'
      preLoaderRoute: typeof NameRecordsRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/history': {
      id: '/$name/history'
      path: '/history'
      fullPath: '/$name/history'
      preLoaderRoute: typeof NameHistoryRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/edit-records': {
      id: '/$name/edit-records'
      path: '/edit-records'
      fullPath: '/$name/edit-records'
      preLoaderRoute: typeof NameEditRecordsRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/create-subname': {
      id: '/$name/create-subname'
      path: '/create-subname'
      fullPath: '/$name/create-subname'
      preLoaderRoute: typeof NameCreateSubnameRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/change-resolver': {
      id: '/$name/change-resolver'
      path: '/change-resolver'
      fullPath: '/$name/change-resolver'
      preLoaderRoute: typeof NameChangeResolverRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/address': {
      id: '/$name/address'
      path: '/address'
      fullPath: '/$name/address'
      preLoaderRoute: typeof NameAddressRouteImport
      parentRoute: typeof NameRoute
    }
    '/tld/$tld/': {
      id: '/tld/$tld/'
      path: '/'
      fullPath: '/tld/$tld/'
      preLoaderRoute: typeof TldTldIndexRouteImport
      parentRoute: typeof TldTldRoute
    }
    '/resolver/$address/': {
      id: '/resolver/$address/'
      path: '/'
      fullPath: '/resolver/$address/'
      preLoaderRoute: typeof ResolverAddressIndexRouteImport
      parentRoute: typeof ResolverAddressRoute
    }
    '/registry/$address/': {
      id: '/registry/$address/'
      path: '/'
      fullPath: '/registry/$address/'
      preLoaderRoute: typeof RegistryAddressIndexRouteImport
      parentRoute: typeof RegistryAddressRoute
    }
    '/addr/$addr/': {
      id: '/addr/$addr/'
      path: '/'
      fullPath: '/addr/$addr/'
      preLoaderRoute: typeof AddrAddrIndexRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/$name/roles/': {
      id: '/$name/roles/'
      path: '/roles'
      fullPath: '/$name/roles/'
      preLoaderRoute: typeof NameRolesIndexRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/ownership/': {
      id: '/$name/ownership/'
      path: '/ownership'
      fullPath: '/$name/ownership/'
      preLoaderRoute: typeof NameOwnershipIndexRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/fuses/': {
      id: '/$name/fuses/'
      path: '/fuses'
      fullPath: '/$name/fuses/'
      preLoaderRoute: typeof NameFusesIndexRouteImport
      parentRoute: typeof NameRoute
    }
    '/resolver/$address/nodes': {
      id: '/resolver/$address/nodes'
      path: '/nodes'
      fullPath: '/resolver/$address/nodes'
      preLoaderRoute: typeof ResolverAddressNodesRouteImport
      parentRoute: typeof ResolverAddressRoute
    }
    '/resolver/$address/history': {
      id: '/resolver/$address/history'
      path: '/history'
      fullPath: '/resolver/$address/history'
      preLoaderRoute: typeof ResolverAddressHistoryRouteImport
      parentRoute: typeof ResolverAddressRoute
    }
    '/resolver/$address/create-alias': {
      id: '/resolver/$address/create-alias'
      path: '/create-alias'
      fullPath: '/resolver/$address/create-alias'
      preLoaderRoute: typeof ResolverAddressCreateAliasRouteImport
      parentRoute: typeof ResolverAddressRoute
    }
    '/resolver/$address/aliases': {
      id: '/resolver/$address/aliases'
      path: '/aliases'
      fullPath: '/resolver/$address/aliases'
      preLoaderRoute: typeof ResolverAddressAliasesRouteImport
      parentRoute: typeof ResolverAddressRoute
    }
    '/registry/$address/roles': {
      id: '/registry/$address/roles'
      path: '/roles'
      fullPath: '/registry/$address/roles'
      preLoaderRoute: typeof RegistryAddressRolesRouteImport
      parentRoute: typeof RegistryAddressRoute
    }
    '/registry/$address/labels': {
      id: '/registry/$address/labels'
      path: '/labels'
      fullPath: '/registry/$address/labels'
      preLoaderRoute: typeof RegistryAddressLabelsRouteImport
      parentRoute: typeof RegistryAddressRoute
    }
    '/registry/$address/history': {
      id: '/registry/$address/history'
      path: '/history'
      fullPath: '/registry/$address/history'
      preLoaderRoute: typeof RegistryAddressHistoryRouteImport
      parentRoute: typeof RegistryAddressRoute
    }
    '/addr/$addr/reverse-resolution': {
      id: '/addr/$addr/reverse-resolution'
      path: '/reverse-resolution'
      fullPath: '/addr/$addr/reverse-resolution'
      preLoaderRoute: typeof AddrAddrReverseResolutionRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/addr/$addr/resolution': {
      id: '/addr/$addr/resolution'
      path: '/resolution'
      fullPath: '/addr/$addr/resolution'
      preLoaderRoute: typeof AddrAddrResolutionRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/addr/$addr/names': {
      id: '/addr/$addr/names'
      path: '/names'
      fullPath: '/addr/$addr/names'
      preLoaderRoute: typeof AddrAddrNamesRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/addr/$addr/history': {
      id: '/addr/$addr/history'
      path: '/history'
      fullPath: '/addr/$addr/history'
      preLoaderRoute: typeof AddrAddrHistoryRouteImport
      parentRoute: typeof AddrAddrRoute
    }
    '/$name/ownership/transfer': {
      id: '/$name/ownership/transfer'
      path: '/ownership/transfer'
      fullPath: '/$name/ownership/transfer'
      preLoaderRoute: typeof NameOwnershipTransferRouteImport
      parentRoute: typeof NameRoute
    }
    '/$name/fuses/burn': {
      id: '/$name/fuses/burn'
      path: '/fuses/burn'
      fullPath: '/$name/fuses/burn'
      preLoaderRoute: typeof NameFusesBurnRouteImport
      parentRoute: typeof NameRoute
    }
    '/resolver/$address/roles/': {
      id: '/resolver/$address/roles/'
      path: '/roles'
      fullPath: '/resolver/$address/roles/'
      preLoaderRoute: typeof ResolverAddressRolesIndexRouteImport
      parentRoute: typeof ResolverAddressRoute
    }
  }
}

interface NameRouteChildren {
  NameAddressRoute: typeof NameAddressRoute
  NameChangeResolverRoute: typeof NameChangeResolverRoute
  NameCreateSubnameRoute: typeof NameCreateSubnameRoute
  NameEditRecordsRoute: typeof NameEditRecordsRoute
  NameHistoryRoute: typeof NameHistoryRoute
  NameRecordsRoute: typeof NameRecordsRoute
  NameRegistryRoute: typeof NameRegistryRoute
  NameResolverRoute: typeof NameResolverRoute
  NameSubnamesRoute: typeof NameSubnamesRoute
  NameTokenRoute: typeof NameTokenRoute
  NameIndexRoute: typeof NameIndexRoute
  NameFusesBurnRoute: typeof NameFusesBurnRoute
  NameOwnershipTransferRoute: typeof NameOwnershipTransferRoute
  NameFusesIndexRoute: typeof NameFusesIndexRoute
  NameOwnershipIndexRoute: typeof NameOwnershipIndexRoute
  NameRolesIndexRoute: typeof NameRolesIndexRoute
}

const NameRouteChildren: NameRouteChildren = {
  NameAddressRoute: NameAddressRoute,
  NameChangeResolverRoute: NameChangeResolverRoute,
  NameCreateSubnameRoute: NameCreateSubnameRoute,
  NameEditRecordsRoute: NameEditRecordsRoute,
  NameHistoryRoute: NameHistoryRoute,
  NameRecordsRoute: NameRecordsRoute,
  NameRegistryRoute: NameRegistryRoute,
  NameResolverRoute: NameResolverRoute,
  NameSubnamesRoute: NameSubnamesRoute,
  NameTokenRoute: NameTokenRoute,
  NameIndexRoute: NameIndexRoute,
  NameFusesBurnRoute: NameFusesBurnRoute,
  NameOwnershipTransferRoute: NameOwnershipTransferRoute,
  NameFusesIndexRoute: NameFusesIndexRoute,
  NameOwnershipIndexRoute: NameOwnershipIndexRoute,
  NameRolesIndexRoute: NameRolesIndexRoute,
}

const NameRouteWithChildren = NameRoute._addFileChildren(NameRouteChildren)

interface AddrAddrRouteChildren {
  AddrAddrHistoryRoute: typeof AddrAddrHistoryRoute
  AddrAddrNamesRoute: typeof AddrAddrNamesRoute
  AddrAddrResolutionRoute: typeof AddrAddrResolutionRoute
  AddrAddrReverseResolutionRoute: typeof AddrAddrReverseResolutionRoute
  AddrAddrIndexRoute: typeof AddrAddrIndexRoute
}

const AddrAddrRouteChildren: AddrAddrRouteChildren = {
  AddrAddrHistoryRoute: AddrAddrHistoryRoute,
  AddrAddrNamesRoute: AddrAddrNamesRoute,
  AddrAddrResolutionRoute: AddrAddrResolutionRoute,
  AddrAddrReverseResolutionRoute: AddrAddrReverseResolutionRoute,
  AddrAddrIndexRoute: AddrAddrIndexRoute,
}

const AddrAddrRouteWithChildren = AddrAddrRoute._addFileChildren(
  AddrAddrRouteChildren,
)

interface RegistryAddressRouteChildren {
  RegistryAddressHistoryRoute: typeof RegistryAddressHistoryRoute
  RegistryAddressLabelsRoute: typeof RegistryAddressLabelsRoute
  RegistryAddressRolesRoute: typeof RegistryAddressRolesRoute
  RegistryAddressIndexRoute: typeof RegistryAddressIndexRoute
}

const RegistryAddressRouteChildren: RegistryAddressRouteChildren = {
  RegistryAddressHistoryRoute: RegistryAddressHistoryRoute,
  RegistryAddressLabelsRoute: RegistryAddressLabelsRoute,
  RegistryAddressRolesRoute: RegistryAddressRolesRoute,
  RegistryAddressIndexRoute: RegistryAddressIndexRoute,
}

const RegistryAddressRouteWithChildren = RegistryAddressRoute._addFileChildren(
  RegistryAddressRouteChildren,
)

interface ResolverAddressRouteChildren {
  ResolverAddressAliasesRoute: typeof ResolverAddressAliasesRoute
  ResolverAddressCreateAliasRoute: typeof ResolverAddressCreateAliasRoute
  ResolverAddressHistoryRoute: typeof ResolverAddressHistoryRoute
  ResolverAddressNodesRoute: typeof ResolverAddressNodesRoute
  ResolverAddressIndexRoute: typeof ResolverAddressIndexRoute
  ResolverAddressRolesIndexRoute: typeof ResolverAddressRolesIndexRoute
}

const ResolverAddressRouteChildren: ResolverAddressRouteChildren = {
  ResolverAddressAliasesRoute: ResolverAddressAliasesRoute,
  ResolverAddressCreateAliasRoute: ResolverAddressCreateAliasRoute,
  ResolverAddressHistoryRoute: ResolverAddressHistoryRoute,
  ResolverAddressNodesRoute: ResolverAddressNodesRoute,
  ResolverAddressIndexRoute: ResolverAddressIndexRoute,
  ResolverAddressRolesIndexRoute: ResolverAddressRolesIndexRoute,
}

const ResolverAddressRouteWithChildren = ResolverAddressRoute._addFileChildren(
  ResolverAddressRouteChildren,
)

interface TldTldRouteChildren {
  TldTldIndexRoute: typeof TldTldIndexRoute
}

const TldTldRouteChildren: TldTldRouteChildren = {
  TldTldIndexRoute: TldTldIndexRoute,
}

const TldTldRouteWithChildren =
  TldTldRoute._addFileChildren(TldTldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRouteWithChildren,
  AddrAddrRoute: AddrAddrRouteWithChildren,
  RegistryAddressRoute: RegistryAddressRouteWithChildren,
  ResolverAddressRoute: ResolverAddressRouteWithChildren,
  TldTldRoute: TldTldRouteWithChildren,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
