/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NameRouteRouteImport } from './routes/$name/route'
import { Route as AddressRouteRouteImport } from './routes/$address/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutoRenewalIndexRouteImport } from './routes/auto-renewal/index'
import { Route as NameIndexRouteImport } from './routes/$name/index'
import { Route as AddressIndexRouteImport } from './routes/$address/index'
import { Route as RenewNameRouteImport } from './routes/renew/$name'
import { Route as RenewV1NameRouteImport } from './routes/renew-v1/$name'
import { Route as RegisterNameRouteImport } from './routes/register/$name'
import { Route as PaymentListRouteImport } from './routes/payment/list'
import { Route as PaymentAddRouteImport } from './routes/payment/add'
import { Route as MigrationNftRouteImport } from './routes/migration_.nft'
import { Route as LegalTrademarkGuidelinesRouteImport } from './routes/legal/trademark-guidelines'
import { Route as LegalTermsOfUseRouteImport } from './routes/legal/terms-of-use'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as NotificationsAuthenticatedRouteRouteImport } from './routes/notifications/_authenticated/route'
import { Route as PNameIndexRouteImport } from './routes/p/$name/index'
import { Route as NotificationsAuthenticatedIndexRouteImport } from './routes/notifications/_authenticated/index'
import { Route as DebugBackendIndexRouteImport } from './routes/debug/backend/index'
import { Route as DebugBackendSettingsRouteImport } from './routes/debug/backend/settings'
import { Route as NotificationsAuthenticatedSettingsIndexRouteImport } from './routes/notifications/_authenticated/settings/index'
import { Route as NotificationsChannelsEmailVerifyRouteImport } from './routes/notifications/channels/email/verify'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRouteRoute = NameRouteRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRouteRoute = AddressRouteRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoRenewalIndexRoute = AutoRenewalIndexRouteImport.update({
  id: '/auto-renewal/',
  path: '/auto-renewal/',
  getParentRoute: () => rootRouteImport,
} as any)
const NameIndexRoute = NameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NameRouteRoute,
} as any)
const AddressIndexRoute = AddressIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AddressRouteRoute,
} as any)
const RenewNameRoute = RenewNameRouteImport.update({
  id: '/renew/$name',
  path: '/renew/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewV1NameRoute = RenewV1NameRouteImport.update({
  id: '/renew-v1/$name',
  path: '/renew-v1/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterNameRoute = RegisterNameRouteImport.update({
  id: '/register/$name',
  path: '/register/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentListRoute = PaymentListRouteImport.update({
  id: '/payment/list',
  path: '/payment/list',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentAddRoute = PaymentAddRouteImport.update({
  id: '/payment/add',
  path: '/payment/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationNftRoute = MigrationNftRouteImport.update({
  id: '/migration_/nft',
  path: '/migration/nft',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTrademarkGuidelinesRoute =
  LegalTrademarkGuidelinesRouteImport.update({
    id: '/legal/trademark-guidelines',
    path: '/legal/trademark-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalTermsOfUseRoute = LegalTermsOfUseRouteImport.update({
  id: '/legal/terms-of-use',
  path: '/legal/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsAuthenticatedRouteRoute =
  NotificationsAuthenticatedRouteRouteImport.update({
    id: '/notifications/_authenticated',
    path: '/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const PNameIndexRoute = PNameIndexRouteImport.update({
  id: '/p/$name/',
  path: '/p/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsAuthenticatedIndexRoute =
  NotificationsAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NotificationsAuthenticatedRouteRoute,
  } as any)
const DebugBackendIndexRoute = DebugBackendIndexRouteImport.update({
  id: '/debug/backend/',
  path: '/debug/backend/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugBackendSettingsRoute = DebugBackendSettingsRouteImport.update({
  id: '/debug/backend/settings',
  path: '/debug/backend/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsAuthenticatedSettingsIndexRoute =
  NotificationsAuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => NotificationsAuthenticatedRouteRoute,
  } as any)
const NotificationsChannelsEmailVerifyRoute =
  NotificationsChannelsEmailVerifyRouteImport.update({
    id: '/notifications/channels/email/verify',
    path: '/notifications/channels/email/verify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$address': typeof AddressRouteRouteWithChildren
  '/$name': typeof NameRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/migration': typeof MigrationRoute
  '/wallet': typeof WalletRoute
  '/notifications': typeof NotificationsAuthenticatedRouteRouteWithChildren
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/legal/trademark-guidelines': typeof LegalTrademarkGuidelinesRoute
  '/migration/nft': typeof MigrationNftRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/register/$name': typeof RegisterNameRoute
  '/renew-v1/$name': typeof RenewV1NameRoute
  '/renew/$name': typeof RenewNameRoute
  '/$address/': typeof AddressIndexRoute
  '/$name/': typeof NameIndexRoute
  '/auto-renewal/': typeof AutoRenewalIndexRoute
  '/debug/backend/settings': typeof DebugBackendSettingsRoute
  '/debug/backend/': typeof DebugBackendIndexRoute
  '/notifications/': typeof NotificationsAuthenticatedIndexRoute
  '/p/$name/': typeof PNameIndexRoute
  '/notifications/channels/email/verify': typeof NotificationsChannelsEmailVerifyRoute
  '/notifications/settings/': typeof NotificationsAuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/migration': typeof MigrationRoute
  '/wallet': typeof WalletRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/legal/trademark-guidelines': typeof LegalTrademarkGuidelinesRoute
  '/migration/nft': typeof MigrationNftRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/register/$name': typeof RegisterNameRoute
  '/renew-v1/$name': typeof RenewV1NameRoute
  '/renew/$name': typeof RenewNameRoute
  '/$address': typeof AddressIndexRoute
  '/$name': typeof NameIndexRoute
  '/auto-renewal': typeof AutoRenewalIndexRoute
  '/debug/backend/settings': typeof DebugBackendSettingsRoute
  '/debug/backend': typeof DebugBackendIndexRoute
  '/notifications': typeof NotificationsAuthenticatedIndexRoute
  '/p/$name': typeof PNameIndexRoute
  '/notifications/channels/email/verify': typeof NotificationsChannelsEmailVerifyRoute
  '/notifications/settings': typeof NotificationsAuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$address': typeof AddressRouteRouteWithChildren
  '/$name': typeof NameRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/migration': typeof MigrationRoute
  '/wallet': typeof WalletRoute
  '/notifications/_authenticated': typeof NotificationsAuthenticatedRouteRouteWithChildren
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/legal/trademark-guidelines': typeof LegalTrademarkGuidelinesRoute
  '/migration_/nft': typeof MigrationNftRoute
  '/payment/add': typeof PaymentAddRoute
  '/payment/list': typeof PaymentListRoute
  '/register/$name': typeof RegisterNameRoute
  '/renew-v1/$name': typeof RenewV1NameRoute
  '/renew/$name': typeof RenewNameRoute
  '/$address/': typeof AddressIndexRoute
  '/$name/': typeof NameIndexRoute
  '/auto-renewal/': typeof AutoRenewalIndexRoute
  '/debug/backend/settings': typeof DebugBackendSettingsRoute
  '/debug/backend/': typeof DebugBackendIndexRoute
  '/notifications/_authenticated/': typeof NotificationsAuthenticatedIndexRoute
  '/p/$name/': typeof PNameIndexRoute
  '/notifications/channels/email/verify': typeof NotificationsChannelsEmailVerifyRoute
  '/notifications/_authenticated/settings/': typeof NotificationsAuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$address'
    | '/$name'
    | '/dashboard'
    | '/migration'
    | '/wallet'
    | '/notifications'
    | '/legal/privacy-policy'
    | '/legal/terms-of-use'
    | '/legal/trademark-guidelines'
    | '/migration/nft'
    | '/payment/add'
    | '/payment/list'
    | '/register/$name'
    | '/renew-v1/$name'
    | '/renew/$name'
    | '/$address/'
    | '/$name/'
    | '/auto-renewal/'
    | '/debug/backend/settings'
    | '/debug/backend/'
    | '/notifications/'
    | '/p/$name/'
    | '/notifications/channels/email/verify'
    | '/notifications/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/migration'
    | '/wallet'
    | '/legal/privacy-policy'
    | '/legal/terms-of-use'
    | '/legal/trademark-guidelines'
    | '/migration/nft'
    | '/payment/add'
    | '/payment/list'
    | '/register/$name'
    | '/renew-v1/$name'
    | '/renew/$name'
    | '/$address'
    | '/$name'
    | '/auto-renewal'
    | '/debug/backend/settings'
    | '/debug/backend'
    | '/notifications'
    | '/p/$name'
    | '/notifications/channels/email/verify'
    | '/notifications/settings'
  id:
    | '__root__'
    | '/'
    | '/$address'
    | '/$name'
    | '/dashboard'
    | '/migration'
    | '/wallet'
    | '/notifications/_authenticated'
    | '/legal/privacy-policy'
    | '/legal/terms-of-use'
    | '/legal/trademark-guidelines'
    | '/migration_/nft'
    | '/payment/add'
    | '/payment/list'
    | '/register/$name'
    | '/renew-v1/$name'
    | '/renew/$name'
    | '/$address/'
    | '/$name/'
    | '/auto-renewal/'
    | '/debug/backend/settings'
    | '/debug/backend/'
    | '/notifications/_authenticated/'
    | '/p/$name/'
    | '/notifications/channels/email/verify'
    | '/notifications/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRouteRoute: typeof AddressRouteRouteWithChildren
  NameRouteRoute: typeof NameRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  MigrationRoute: typeof MigrationRoute
  WalletRoute: typeof WalletRoute
  NotificationsAuthenticatedRouteRoute: typeof NotificationsAuthenticatedRouteRouteWithChildren
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfUseRoute: typeof LegalTermsOfUseRoute
  LegalTrademarkGuidelinesRoute: typeof LegalTrademarkGuidelinesRoute
  MigrationNftRoute: typeof MigrationNftRoute
  PaymentAddRoute: typeof PaymentAddRoute
  PaymentListRoute: typeof PaymentListRoute
  RegisterNameRoute: typeof RegisterNameRoute
  RenewV1NameRoute: typeof RenewV1NameRoute
  RenewNameRoute: typeof RenewNameRoute
  AutoRenewalIndexRoute: typeof AutoRenewalIndexRoute
  DebugBackendSettingsRoute: typeof DebugBackendSettingsRoute
  DebugBackendIndexRoute: typeof DebugBackendIndexRoute
  PNameIndexRoute: typeof PNameIndexRoute
  NotificationsChannelsEmailVerifyRoute: typeof NotificationsChannelsEmailVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$address': {
      id: '/$address'
      path: '/$address'
      fullPath: '/$address'
      preLoaderRoute: typeof AddressRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-renewal/': {
      id: '/auto-renewal/'
      path: '/auto-renewal'
      fullPath: '/auto-renewal/'
      preLoaderRoute: typeof AutoRenewalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name/': {
      id: '/$name/'
      path: '/'
      fullPath: '/$name/'
      preLoaderRoute: typeof NameIndexRouteImport
      parentRoute: typeof NameRouteRoute
    }
    '/$address/': {
      id: '/$address/'
      path: '/'
      fullPath: '/$address/'
      preLoaderRoute: typeof AddressIndexRouteImport
      parentRoute: typeof AddressRouteRoute
    }
    '/renew/$name': {
      id: '/renew/$name'
      path: '/renew/$name'
      fullPath: '/renew/$name'
      preLoaderRoute: typeof RenewNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew-v1/$name': {
      id: '/renew-v1/$name'
      path: '/renew-v1/$name'
      fullPath: '/renew-v1/$name'
      preLoaderRoute: typeof RenewV1NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$name': {
      id: '/register/$name'
      path: '/register/$name'
      fullPath: '/register/$name'
      preLoaderRoute: typeof RegisterNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/list': {
      id: '/payment/list'
      path: '/payment/list'
      fullPath: '/payment/list'
      preLoaderRoute: typeof PaymentListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/add': {
      id: '/payment/add'
      path: '/payment/add'
      fullPath: '/payment/add'
      preLoaderRoute: typeof PaymentAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration_/nft': {
      id: '/migration_/nft'
      path: '/migration/nft'
      fullPath: '/migration/nft'
      preLoaderRoute: typeof MigrationNftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/trademark-guidelines': {
      id: '/legal/trademark-guidelines'
      path: '/legal/trademark-guidelines'
      fullPath: '/legal/trademark-guidelines'
      preLoaderRoute: typeof LegalTrademarkGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-use': {
      id: '/legal/terms-of-use'
      path: '/legal/terms-of-use'
      fullPath: '/legal/terms-of-use'
      preLoaderRoute: typeof LegalTermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/_authenticated': {
      id: '/notifications/_authenticated'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$name/': {
      id: '/p/$name/'
      path: '/p/$name'
      fullPath: '/p/$name/'
      preLoaderRoute: typeof PNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/_authenticated/': {
      id: '/notifications/_authenticated/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsAuthenticatedIndexRouteImport
      parentRoute: typeof NotificationsAuthenticatedRouteRoute
    }
    '/debug/backend/': {
      id: '/debug/backend/'
      path: '/debug/backend'
      fullPath: '/debug/backend/'
      preLoaderRoute: typeof DebugBackendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/backend/settings': {
      id: '/debug/backend/settings'
      path: '/debug/backend/settings'
      fullPath: '/debug/backend/settings'
      preLoaderRoute: typeof DebugBackendSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/_authenticated/settings/': {
      id: '/notifications/_authenticated/settings/'
      path: '/settings'
      fullPath: '/notifications/settings/'
      preLoaderRoute: typeof NotificationsAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof NotificationsAuthenticatedRouteRoute
    }
    '/notifications/channels/email/verify': {
      id: '/notifications/channels/email/verify'
      path: '/notifications/channels/email/verify'
      fullPath: '/notifications/channels/email/verify'
      preLoaderRoute: typeof NotificationsChannelsEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AddressRouteRouteChildren {
  AddressIndexRoute: typeof AddressIndexRoute
}

const AddressRouteRouteChildren: AddressRouteRouteChildren = {
  AddressIndexRoute: AddressIndexRoute,
}

const AddressRouteRouteWithChildren = AddressRouteRoute._addFileChildren(
  AddressRouteRouteChildren,
)

interface NameRouteRouteChildren {
  NameIndexRoute: typeof NameIndexRoute
}

const NameRouteRouteChildren: NameRouteRouteChildren = {
  NameIndexRoute: NameIndexRoute,
}

const NameRouteRouteWithChildren = NameRouteRoute._addFileChildren(
  NameRouteRouteChildren,
)

interface NotificationsAuthenticatedRouteRouteChildren {
  NotificationsAuthenticatedIndexRoute: typeof NotificationsAuthenticatedIndexRoute
  NotificationsAuthenticatedSettingsIndexRoute: typeof NotificationsAuthenticatedSettingsIndexRoute
}

const NotificationsAuthenticatedRouteRouteChildren: NotificationsAuthenticatedRouteRouteChildren =
  {
    NotificationsAuthenticatedIndexRoute: NotificationsAuthenticatedIndexRoute,
    NotificationsAuthenticatedSettingsIndexRoute:
      NotificationsAuthenticatedSettingsIndexRoute,
  }

const NotificationsAuthenticatedRouteRouteWithChildren =
  NotificationsAuthenticatedRouteRoute._addFileChildren(
    NotificationsAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRouteRoute: AddressRouteRouteWithChildren,
  NameRouteRoute: NameRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  MigrationRoute: MigrationRoute,
  WalletRoute: WalletRoute,
  NotificationsAuthenticatedRouteRoute:
    NotificationsAuthenticatedRouteRouteWithChildren,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfUseRoute: LegalTermsOfUseRoute,
  LegalTrademarkGuidelinesRoute: LegalTrademarkGuidelinesRoute,
  MigrationNftRoute: MigrationNftRoute,
  PaymentAddRoute: PaymentAddRoute,
  PaymentListRoute: PaymentListRoute,
  RegisterNameRoute: RegisterNameRoute,
  RenewV1NameRoute: RenewV1NameRoute,
  RenewNameRoute: RenewNameRoute,
  AutoRenewalIndexRoute: AutoRenewalIndexRoute,
  DebugBackendSettingsRoute: DebugBackendSettingsRoute,
  DebugBackendIndexRoute: DebugBackendIndexRoute,
  PNameIndexRoute: PNameIndexRoute,
  NotificationsChannelsEmailVerifyRoute: NotificationsChannelsEmailVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
