/// <reference types="vite/client" />

// Generated by wrangler using `pnpm cf-typegen`
interface ImportMetaEnv extends Readonly<Cloudflare.Env> {}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
