#!/usr/bin/env bash
# Seed an Anvil state snapshot from a Sepolia fork.
# Output: e2e/infra/anvil/state.json
#
# Anvil is run via Docker (ghcr.io/foundry-rs/foundry:latest) so the state
# is always generated by the same binary version used in the snapshot image.
#
# Usage:
#   SEPOLIA_FORK_URL=https://... ./seed-state.sh
#   SEPOLIA_FORK_URL=... SEPOLIA_FORK_BLOCK=9400000 ./seed-state.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/.."
ANVIL_DIR="$INFRA_DIR/anvil"
STATE_FILE="$ANVIL_DIR/state.json"
FOUNDRY_IMAGE="ghcr.io/foundry-rs/foundry:latest"
CONTAINER_NAME="ens-anvil-seed"
RPC_URL="http://127.0.0.1:8545"

FORK_URL="${SEPOLIA_FORK_URL:?Set SEPOLIA_FORK_URL to a Sepolia RPC endpoint}"
FORK_BLOCK="${SEPOLIA_FORK_BLOCK:-}"

mkdir -p "$ANVIL_DIR"

# Ensure no leftover container from a previous run
docker rm -f "$CONTAINER_NAME" > /dev/null 2>&1 || true

cleanup() {
  docker rm -f "$CONTAINER_NAME" > /dev/null 2>&1 || true
}
trap cleanup EXIT

# Pull the image if not already present (skip gracefully on auth issues)
if ! docker image inspect "$FOUNDRY_IMAGE" > /dev/null 2>&1; then
  echo "=== Pulling Foundry image ==="
  docker pull "$FOUNDRY_IMAGE"
fi

ANVIL_ARGS=(
  --fork-url "$FORK_URL"
  --chain-id 11155111
  --port 8545
  --host 0.0.0.0
  --quiet
)
[[ -n "$FORK_BLOCK" ]] && ANVIL_ARGS+=(--fork-block-number "$FORK_BLOCK")

echo ""
echo "=== Starting Anvil fork via Docker (allow 30-60s for fork init) ==="
docker run -d \
  --name "$CONTAINER_NAME" \
  -p 8545:8545 \
  --entrypoint anvil \
  "$FOUNDRY_IMAGE" \
  "${ANVIL_ARGS[@]}"

# Wait for RPC to be ready (using local cast or curl)
elapsed=0
until curl -sf -X POST http://127.0.0.1:8545 \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' > /dev/null 2>&1; do
  sleep 2; elapsed=$((elapsed + 2))
  if [ $elapsed -ge 120 ]; then echo "ERROR: Anvil did not start within 120s"; exit 1; fi
done
echo "Anvil ready"

# Bake all required contracts into the local fork state.
# anvil_dumpState only serialises accounts that were written locally; reads into
# the fork cache are not included. For each contract we:
#   1. anvil_setCode  — forces bytecode into the modified-accounts set
#   2. scan slots 0-127 — picks up all sequentially-laid-out state variables
#   3. compute & copy critical hash-addressed mapping slots (payment ratios, roles)
echo ""
echo "=== Baking contracts into fork state ==="
FOUNDRY_DISABLE_NIGHTLY_WARNING=1 python3 "$SCRIPT_DIR/bake-contracts.py" "$RPC_URL"

# Fund all known test accounts
echo ""
echo "=== Funding accounts ==="
bash "$SCRIPT_DIR/fund-account.sh" "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
bash "$SCRIPT_DIR/fund-rhinestone-account.sh"

# Dump state via anvil_dumpState RPC — returns gzip-compressed JSON as a hex string.
# Pipe directly through Python to avoid shell variable size limits.
echo ""
echo "=== Dumping state via anvil_dumpState RPC ==="
curl -sf -X POST "$RPC_URL" \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"anvil_dumpState","params":[],"id":1}' \
  | python3 -c "
import sys, json, binascii, gzip
data = json.load(sys.stdin)
h = data['result']
if h.startswith('0x'): h = h[2:]
sys.stdout.buffer.write(gzip.decompress(binascii.unhexlify(h)))
" > "$STATE_FILE"

if [[ ! -s "$STATE_FILE" ]]; then
  echo "ERROR: anvil_dumpState wrote empty file"
  docker logs "$CONTAINER_NAME" | tail -20
  exit 1
fi

echo "=== Stopping container ==="
docker stop "$CONTAINER_NAME" > /dev/null

docker rm "$CONTAINER_NAME" > /dev/null 2>&1 || true
trap - EXIT

# Update contracts.snapshot.json with the snapshot block so Panoptes starts there.
SNAPSHOT_BLOCK=$(python3 -c "
import json, sys
with open('$STATE_FILE') as f:
    print(int(json.load(f)['block']['number'], 16))
")
CONTRACTS_BOX="$INFRA_DIR/panoptes/contracts.snapshot.json"
python3 -c "
import json, sys
path, block = sys.argv[1], int(sys.argv[2])
with open(path) as f:
    c = json.load(f)
c['l2_deployment_block'] = block
with open(path, 'w') as f:
    json.dump(c, f, indent=2)
print('Updated l2_deployment_block =', block)
" "$CONTRACTS_BOX" "$SNAPSHOT_BLOCK"

SIZE=$(wc -c < "$STATE_FILE")
echo "State saved to $STATE_FILE ($SIZE bytes)"
echo ""
echo "Next:"
echo "  docker build -f e2e/infra/Dockerfile.anvil-snapshot \\"
echo "    -t ghcr.io/ensdomains/ens-v2-snapshot:latest e2e/infra"
